// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG9wcVlrhU98Wj5HqqxErCrYN6gxxnh_0',
    appId: '1:984935343154:web:78883da90172d21ab1482b',
    messagingSenderId: '984935343154',
    projectId: 'scholarship-sponser-finder',
    authDomain: 'scholarship-sponser-finder.firebaseapp.com',
    storageBucket: 'scholarship-sponser-finder.firebasestorage.app',
    measurementId: 'G-2TF4WL1X39',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4ddHIjs9nnGHGukP5obdw6kpb7O77FRE',
    appId: '1:984935343154:android:e56fd0ef02f1d67bb1482b',
    messagingSenderId: '984935343154',
    projectId: 'scholarship-sponser-finder',
    storageBucket: 'scholarship-sponser-finder.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQD4lha0nKSMWmnQUF_Mu4sq2nMH2SDtM',
    appId: '1:984935343154:ios:bf8c3eca35dce4ddb1482b',
    messagingSenderId: '984935343154',
    projectId: 'scholarship-sponser-finder',
    storageBucket: 'scholarship-sponser-finder.firebasestorage.app',
    iosClientId: '984935343154-m2mjro1ovq76usfh58ggdc0545s6ckfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarshipSponserConnectPlatform',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQD4lha0nKSMWmnQUF_Mu4sq2nMH2SDtM',
    appId: '1:984935343154:ios:bf8c3eca35dce4ddb1482b',
    messagingSenderId: '984935343154',
    projectId: 'scholarship-sponser-finder',
    storageBucket: 'scholarship-sponser-finder.firebasestorage.app',
    iosClientId: '984935343154-m2mjro1ovq76usfh58ggdc0545s6ckfk.apps.googleusercontent.com',
    iosBundleId: 'com.example.scholarshipSponserConnectPlatform',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG9wcVlrhU98Wj5HqqxErCrYN6gxxnh_0',
    appId: '1:984935343154:web:b7f23790c929741ab1482b',
    messagingSenderId: '984935343154',
    projectId: 'scholarship-sponser-finder',
    authDomain: 'scholarship-sponser-finder.firebaseapp.com',
    storageBucket: 'scholarship-sponser-finder.firebasestorage.app',
    measurementId: 'G-0CC8TV6GDJ',
  );
}
